CLASS zlyz210_bp_traveltp_sol DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zlyz210_r_traveltp_sol .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zlyz210_bp_traveltp_sol IMPLEMENTATION.
ENDCLASS.
