CLASS zlyz110_travel_event_handl_sol DEFINITION
  PUBLIC
  FINAL FOR EVENTS OF zlyz110_r_traveltp_sol
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zlyz110_travel_event_handl_sol IMPLEMENTATION.
ENDCLASS.
